### PR TITLE
feat(s3_age_metric): find the oldest object in s3

### PR DESCRIPTION
**Pull request by roleyfoley**
Find the oldest object in an S3 bucket and records the age of the item
in seconds as a cloudwatch metric

Includes the code itself along with a hamlet module to deploy it

### CODE REVIEW

**Comment by RossMurr4y** [comment]
It's still up for discussion in a PR but could we try out the [README template](https://github.com/hamlet-io/hamlet-library/pull/2)? 

The README's as they are are pretty minimal and require me to dig through the implementation of the modules to work out how to use them.

**Comment by roleyfoley** [comment]
> It's still up for discussion in a PR but could we try out the [README template](https://github.com/hamlet-io/hamlet-library/pull/2)?
> 
> The README's as they are are pretty minimal and require me to dig through the implementation of the modules to work out how to use them.

Added, it felt like I just copied the code into a README file though for most of it. Which feels really dangerous from an accuracy perspective

**Comment by RossMurr4y** [comment]
I agree. Just created hamlet-io/engine#1550 to introduce module schemas to the engine. This would allow all providers to easily produce the structure and keep it updated. Does that work for you?

**Comment by roleyfoley** [comment]
@RossMurr4y Happy with the schema, much easier to handle from the config side. 

Not sure what we should do for the solution side though. I think we need something to say what it would look like, copying out the solution blueprint is duplicatating even more than the initial config. Lets go with this for now

**Pull request merged**
